"""Config flow for the Concierge MCP integration.

The guest secret is generated by the integration, never supplied by the
operator (FR-6), and is shown exactly once during setup — Home Assistant
does not retain a way to display it again afterward, so the operator must
copy it now or regenerate it later via the options flow.
"""
from __future__ import annotations

from typing import Any

import voluptuous as vol
from homeassistant.config_entries import ConfigEntry, ConfigFlow, ConfigFlowResult

from . import auth
from .const import CONF_ENTITIES, CONF_SECRET, DEFAULT_NAME, DOMAIN
from .options_flow import ConciergeMCPOptionsFlow


class ConciergeMCPConfigFlow(ConfigFlow, domain=DOMAIN):
    """Handle the (single-instance) initial setup flow."""

    VERSION = 1

    def __init__(self) -> None:
        self._secret: str | None = None

    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult:
        # No explicit single-instance check needed here: manifest.json's
        # "single_config_entry": true makes the flow framework itself abort
        # with reason "single_instance_allowed" before this step ever runs,
        # for any second attempt to add this integration.
        if user_input is not None:
            self._secret = auth.generate_secret()
            return await self.async_step_show_secret()

        return self.async_show_form(step_id="user")

    async def async_step_show_secret(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        if user_input is not None:
            return self.async_create_entry(
                title=DEFAULT_NAME,
                data={CONF_SECRET: self._secret},
                options={CONF_ENTITIES: []},
            )

        return self.async_show_form(
            step_id="show_secret",
            data_schema=vol.Schema({}),
            description_placeholders={"secret": self._secret},
        )

    @staticmethod
    def async_get_options_flow(config_entry: ConfigEntry) -> ConciergeMCPOptionsFlow:
        return ConciergeMCPOptionsFlow(config_entry)
